services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      LOAD_OPTIMIZER_STRATEGY: ${LOAD_OPTIMIZER_STRATEGY}
      LOAD_OPTIMIZER_WEIGHTS_PAYOUT: ${LOAD_OPTIMIZER_WEIGHTS_PAYOUT}
      LOAD_OPTIMIZER_WEIGHTS_WEIGHT_UTILIZATION: ${LOAD_OPTIMIZER_WEIGHTS_WEIGHT_UTILIZATION}
      LOAD_OPTIMIZER_WEIGHTS_VOLUME_UTILIZATION: ${LOAD_OPTIMIZER_WEIGHTS_VOLUME_UTILIZATION}